Call "%~dp0install microsoft visual c++ redistributable.bat"
Call "%~dp0install altsnap.bat"
Call "%~dp0install arduino.bat"
Call "%~dp0install blender.bat"
Call "%~dp0install chocolatey.bat"
REM Call "%~dp0install eartrumpet.bat"
Call "%~dp0install edge redirect.bat"
Call "%~dp0install gajim.bat"
Call "%~dp0install hardlink shell extension.bat"
Call "%~dp0install inkscape.bat"
Call "%~dp0install irfanview plugins.bat"
Call "%~dp0install irfanview.bat"
Call "%~dp0install kicad.bat"
Call "%~dp0install libreoffice.bat"
Call "%~dp0install mumble.bat"
Call "%~dp0install nvidia.bat"
Call "%~dp0install notepad++.bat"
Call "%~dp0install origin.bat"
Call "%~dp0install openshot.bat"
Call "%~dp0install paint.net.bat"
Call "%~dp0install powertoys.bat"
Call "%~dp0install putty.bat"
Call "%~dp0install shotcut.bat"
Call "%~dp0install sketchup.bat"
Call "%~dp0install steam.bat"
Call "%~dp0install streamdeck.bat"
Call "%~dp0install sumatra.bat"
Call "%~dp0install thunderbird.bat"
Call "%~dp0install vlc.bat"
Call "%~dp0install wacup.bat"
Call "%~dp0install winscp.bat"
